complected chages

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -20,9 +20,12 @@ jobs:
     - name: Run Playwright tests
       run: npx playwright test
 
+    # - name: Run tests
+    #   run: |
+    #     npx playwright test || echo "Tests failed, but proceeding."
+
     - name: Run tests
-      run: |
-        npx playwright test || echo "Tests failed, but proceeding."
+      run: npx playwright test --trace on    
 
     - uses: actions/upload-artifact@v4
       if: ${{ !cancelled() }}
